#include <iostream>
#include <string>

using namespace std;
int main()
{
   string raptor_prompt_variable_zzyz;
   ?? b;
   ?? result;
   ?? a;

   raptor_prompt_variable_zzyz ="Ener first number";
   cout << raptor_prompt_variable_zzyz << endl;
   cin >> a;
   raptor_prompt_variable_zzyz ="Enter the secound number";
   cout << raptor_prompt_variable_zzyz << endl;
   cin >> b;
   result =a+b;
   cout << "Put the result of the addition operation a"+result << endl;
   return 0;
}
